apiVersion: v1
kind: ConfigMap
metadata:
  name: nutrition-config
  namespace: nutriplan
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=nutriplan;Username=postgres;Password=postgres"
