apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
  namespace: nutriplan
  labels:
    app: nutrition-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
    spec:
      containers:
        - name: nutrition-service
          image: maksondep/nutriplan-nutrition:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: nutrition-config
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nutrition-service
  namespace: nutriplan
spec:
  selector:
    app: nutrition-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
