// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionService.Data;

#nullable disable

namespace NutritionService.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionService.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 68.0,
                            CarbsPer100g = 12.0,
                            Category = "breakfast",
                            FatPer100g = 1.3999999999999999,
                            Name = "Вівсянка",
                            ProteinPer100g = 2.3999999999999999
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 155.0,
                            CarbsPer100g = 1.1000000000000001,
                            Category = "breakfast",
                            FatPer100g = 11.0,
                            Name = "Яйця варені",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 165.0,
                            CarbsPer100g = 0.0,
                            Category = "lunch",
                            FatPer100g = 3.6000000000000001,
                            Name = "Куряче філе",
                            ProteinPer100g = 31.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 130.0,
                            CarbsPer100g = 28.0,
                            Category = "lunch",
                            FatPer100g = 0.29999999999999999,
                            Name = "Рис варений",
                            ProteinPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 208.0,
                            CarbsPer100g = 0.0,
                            Category = "dinner",
                            FatPer100g = 13.0,
                            Name = "Лосось",
                            ProteinPer100g = 20.0
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 34.0,
                            CarbsPer100g = 7.0,
                            Category = "dinner",
                            FatPer100g = 0.40000000000000002,
                            Name = "Броколі",
                            ProteinPer100g = 2.7999999999999998
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 654.0,
                            CarbsPer100g = 14.0,
                            Category = "snack",
                            FatPer100g = 65.0,
                            Name = "Грецькі горіхи",
                            ProteinPer100g = 15.0
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 89.0,
                            CarbsPer100g = 23.0,
                            Category = "snack",
                            FatPer100g = 0.29999999999999999,
                            Name = "Банан",
                            ProteinPer100g = 1.1000000000000001
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 135.0,
                            CarbsPer100g = 0.0,
                            Category = "lunch",
                            FatPer100g = 1.0,
                            Name = "Грудка індички",
                            ProteinPer100g = 30.0
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 92.0,
                            CarbsPer100g = 20.0,
                            Category = "lunch",
                            FatPer100g = 0.59999999999999998,
                            Name = "Гречка варена",
                            ProteinPer100g = 3.3999999999999999
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 121.0,
                            CarbsPer100g = 2.0,
                            Category = "breakfast",
                            FatPer100g = 5.0,
                            Name = "Сир кисломолочний 5%",
                            ProteinPer100g = 17.0
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 187.0,
                            CarbsPer100g = 0.0,
                            Category = "dinner",
                            FatPer100g = 9.0,
                            Name = "Яловичина тушкована",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 31.0,
                            CarbsPer100g = 6.0,
                            Category = "dinner",
                            FatPer100g = 0.29999999999999999,
                            Name = "Солодкий перець",
                            ProteinPer100g = 1.0
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 52.0,
                            CarbsPer100g = 4.7999999999999998,
                            Category = "breakfast",
                            FatPer100g = 2.5,
                            Name = "Молоко 2.5%",
                            ProteinPer100g = 2.8999999999999999
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 52.0,
                            CarbsPer100g = 14.0,
                            Category = "snack",
                            FatPer100g = 0.20000000000000001,
                            Name = "Яблуко",
                            ProteinPer100g = 0.29999999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
