{{- if .Values.nutritionService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nutriplan.fullname" . }}-nutrition
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nutriplan.labels" . | nindent 4 }}
    app: nutrition-service
spec:
  type: {{ .Values.nutritionService.service.type }}
  selector:
    app: nutrition-service
  ports:
    - port: {{ .Values.nutritionService.service.port }}
      targetPort: {{ .Values.nutritionService.service.targetPort }}
      {{- if and (eq .Values.nutritionService.service.type "NodePort") .Values.nutritionService.service.nodePort }}
      nodePort: {{ .Values.nutritionService.service.nodePort }}
      {{- end }}
{{- end }}
