nutritionService:
  image:
    repository: nutriplan-nutrition
    tag: latest
    pullPolicy: Never

notificationService:
  image:
    repository: nutriplan-notification
    tag: latest
    pullPolicy: Never